In [1]:

list1 = list(range(1, 26))
print("List1:", list1)
print("Even Numbers:", [n for n in list1 if n % 2 == 0])
print("Sum:", sum(list1))

list2 = [n**2 for n in range(1, 26)]
print("List2:", list2)
print("Squares >100:", [n for n in list2 if n>100])
print("Max Square:", max(list2))

list3 = [n**3 for n in range(1,26)]
print("List3:", list3)
print("Cubes divisible by 5:", [n for n in list3 if n%5==0])
print("Sum of Cubes:", sum(list3))

list4 = [45,78,32,90,66,59,82,73,48,99,67,54,71,38,85,92,41,63,77,88,55,69,60,80,72]
print("List4:", list4)
print("Passed (>40):", [m for m in list4 if m>40])
print("Average:", sum(list4)/len(list4))

list5 = ["Nagpur","Mumbai","Pune","Delhi","Bangalore","Hyderabad","Chennai","Kolkata","Jaipur","Indore",
         "Lucknow","Ahmedabad","Surat","Kanpur","Bhopal","Ranchi","Patna","Raipur","Thane","Nashik",
         "Nagaur","Udaipur","Vadodara","Amritsar","Jodhpur"]
print("List5:", list5)
print("Cities starting with 'N':", [c for c in list5 if c.startswith("N")])

list6 = ["apple","banana","mango","orange","grapes","papaya","kiwi","pear","plum","cherry",
         "peach","pineapple","melon","guava","fig","apricot","dragonfruit","lychee","coconut","strawberry",
         "blueberry","blackberry","pomegranate","date","jackfruit"]
print("List6:", list6)
print("Fruits with 'p':", [f for f in list6 if 'p' in f])

list7 = ["red","blue","green","yellow","black","white","pink","purple","brown","orange",
         "gray","violet","indigo","gold","silver","teal","maroon","navy","turquoise","beige",
         "olive","cyan","magenta","peach","cream"]
print("List7:", list7)
print("Colors containing 'o':", [c for c in list7 if 'o' in c])

list8 = ["Python","Java","C","C++","C","JavaScript","PHP","Ruby","Go","Rust",
         "Kotlin","Swift","R","Scala","Perl","MATLAB","TypeScript","Dart","Objective-C","Fortran",
         "Assembly","Haskell","Lua","Visual Basic","Groovy"]
print("List8:", list8)
print("Languages longer than 6 chars:", [l for l in list8 if len(l)>6])

list9 = [250,450,300,500,750,120,800,650,400,550,600,350,200,900,1000,450,780,670,880,910,540,620,710,810,330]
print("List9:", list9)
print("Prices >500:", [p for p in list9 if p>500])
print("Average Price:", sum(list9)/len(list9))

list10 = [30,32,35,28,40,38,29,27,36,34,31,33,39,37,30,28,29,32,35,31,30,33,36,34,32]
print("List10:", list10)
print("Temperatures >35:", [t for t in list10 if t>35])
print("Max Temperature:", max(list10))

list11 = [18,22,25,21,30,28,26,23,24,27,19,20,22,21,25,29,31,32,28,26,27,24,23,22,20]
print("List11:", list11)
print("Adults >=18:", [a for a in list11 if a>=18])

list12 = [88,76,92,55,64,81,73,69,95,87,79,60,84,77,91,86,80,70,82,65,90,78,83,72,85]
print("List12:", list12)
print("Scores >80:", [s for s in list12 if s>80])

list13 = [10,15,8,12,20,18,25,30,22,17,14,28,19,24,16,21,23,27,26,11,13,9,29,31,32]
print("List13:", list13)
print("Distances >20:", [d for d in list13 if d>20])

list14 = [50,55,60,65,70,75,80,85,90,95,100,45,52,58,62,68,72,77,83,88,93,97,54,59,64]
print("List14:", list14)
print("Weights >70:", [w for w in list14 if w>70])


list15 = [150,155,160,165,170,175,180,185,190,195,152,158,163,168,173,178,183,188,193,198,151,156,161,166,171]
print("List15:", list15)
print("Heights >170:", [h for h in list15 if h>170])


list16 = [25000,30000,35000,40000,45000,50000,55000,60000,65000,70000,32000,37000,42000,47000,52000,57000,62000,67000,72000,77000,33000,38000,43000,48000,53000]
print("List16:", list16)
print("Salaries >50000:", [s for s in list16 if s>50000])


list17 = [23,25,28,30,35,27,26,29,32,31,24,22,33,34,36,38,40,26,28,30,27,29,31,32,33]
print("List17:", list17)
print("Ages >30:", [a for a in list17 if a>30])


list18 = [20,22,25,18,30,28,19,17,26,24,21,23,29,27,20,18,19,22,25,21,20,23,26,24,22]
print("List18:", list18)
print("Temp >25:", [t for t in list18 if t>25])


list19 = [55,60,65,70,75,80,85,90,95,50,52,58,62,68,72,77,83,88,93,97,54,59,64,69,74]
print("List19:", list19)
print("Marks >=70:", [m for m in list19 if m>=70])


list20 = [88,92,76,85,79,91,83,87,95,80,72,68,84,77,90,86,81,78,89,93,75,82,88,94,79]
print("List20:", list20)
print("Scores >85:", [s for s in list20 if s>85])


list21 = [5,8,12,15,20,18,25,30,22,17,14,28,19,24,16,21,23,27,26,11,13,9,29,31,32]
print("List21:", list21)
print("Distances >20:", [d for d in list21 if d>20])


list22 = [120,150,180,200,220,250,280,300,320,350,125,155,185,205,225,255,285,305,325,355,130,160,190,210,230]
print("List22:", list22)
print("Pages >250:", [p for p in list22 if p>250])


list23 = [4.2,3.8,4.5,4.0,3.5,4.8,4.1,3.9,4.6,4.3,4.0,3.7,4.4,4.2,3.9,4.5,4.7,4.1,3.8,4.6,4.3,4.0,4.2,4.4,4.1]
print("List23:", list23)
print("Ratings >=4.5:", [r for r in list23 if r>=4.5])


list24 = [100,150,200,250,300,120,180,220,260,280,140,190,230,270,310,330,170,210,250,290,320,360,380,400,420]
print("List24:", list24)
print("Prices >250:", [p for p in list24 if p>250])


list25 = [50,60,70,80,90,55,65,75,85,95,40,45,55,65,75,85,95,50,60,70,80,90,100,110,120]
print("List25:", list25)
print("Inventory >80:", [i for i in list25 if i>80])
print("Total Inventory:", sum(list25))

List1: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
Even Numbers: [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24]
Sum: 325
List2: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625]
Squares >100: [121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625]
Max Square: 625
List3: [1, 8, 27, 64, 125, 216, 343, 512, 729, 1000, 1331, 1728, 2197, 2744, 3375, 4096, 4913, 5832, 6859, 8000, 9261, 10648, 12167, 13824, 15625]
Cubes divisible by 5: [125, 1000, 3375, 8000, 15625]
Sum of Cubes: 105625
List4: [45, 78, 32, 90, 66, 59, 82, 73, 48, 99, 67, 54, 71, 38, 85, 92, 41, 63, 77, 88, 55, 69, 60, 80, 72]
Passed (>40): [45, 78, 90, 66, 59, 82, 73, 48, 99, 67, 54, 71, 85, 92, 41, 63, 77, 88, 55, 69, 60, 80, 72]
Average: 67.36
List5: ['Nagpur', 'Mumbai', 'Pune', 'Delhi', 'Bangalore', 'Hyderabad', 'Chennai', 'Kolkata', 'Jaipur', 'Indore', 'Lucknow', 'Ahmedabad', 'Surat', 'Kanpur', 'Bhopal', 'Ranchi', 'Patna', 'Raipur', 'Thane', 'Nashik', 'Nagaur', 'Udaipur', 'Vadodara', 'Amritsar', 'Jodhpur']
Cities starting with 'N': ['Nagpur', 'Nashik', 'Nagaur']
List6: ['apple', 'banana', 'mango', 'orange', 'grapes', 'papaya', 'kiwi', 'pear', 'plum', 'cherry', 'peach', 'pineapple', 'melon', 'guava', 'fig', 'apricot', 'dragonfruit', 'lychee', 'coconut', 'strawberry', 'blueberry', 'blackberry', 'pomegranate', 'date', 'jackfruit']
Fruits with 'p': ['apple', 'grapes', 'papaya', 'pear', 'plum', 'peach', 'pineapple', 'apricot', 'pomegranate']
List7: ['red', 'blue', 'green', 'yellow', 'black', 'white', 'pink', 'purple', 'brown', 'orange', 'gray', 'violet', 'indigo', 'gold', 'silver', 'teal', 'maroon', 'navy', 'turquoise', 'beige', 'olive', 'cyan', 'magenta', 'peach', 'cream']
Colors containing 'o': ['yellow', 'brown', 'orange', 'violet', 'indigo', 'gold', 'maroon', 'turquoise', 'olive']
List8: ['Python', 'Java', 'C', 'C++', 'C', 'JavaScript', 'PHP', 'Ruby', 'Go', 'Rust', 'Kotlin', 'Swift', 'R', 'Scala', 'Perl', 'MATLAB', 'TypeScript', 'Dart', 'Objective-C', 'Fortran', 'Assembly', 'Haskell', 'Lua', 'Visual Basic', 'Groovy']
Languages longer than 6 chars: ['JavaScript', 'TypeScript', 'Objective-C', 'Fortran', 'Assembly', 'Haskell', 'Visual Basic']
List9: [250, 450, 300, 500, 750, 120, 800, 650, 400, 550, 600, 350, 200, 900, 1000, 450, 780, 670, 880, 910, 540, 620, 710, 810, 330]
Prices >500: [750, 800, 650, 550, 600, 900, 1000, 780, 670, 880, 910, 540, 620, 710, 810]
Average Price: 580.8
List10: [30, 32, 35, 28, 40, 38, 29, 27, 36, 34, 31, 33, 39, 37, 30, 28, 29, 32, 35, 31, 30, 33, 36, 34, 32]
Temperatures >35: [40, 38, 36, 39, 37, 36]
Max Temperature: 40
List11: [18, 22, 25, 21, 30, 28, 26, 23, 24, 27, 19, 20, 22, 21, 25, 29, 31, 32, 28, 26, 27, 24, 23, 22, 20]
Adults >=18: [18, 22, 25, 21, 30, 28, 26, 23, 24, 27, 19, 20, 22, 21, 25, 29, 31, 32, 28, 26, 27, 24, 23, 22, 20]
List12: [88, 76, 92, 55, 64, 81, 73, 69, 95, 87, 79, 60, 84, 77, 91, 86, 80, 70, 82, 65, 90, 78, 83, 72, 85]
Scores >80: [88, 92, 81, 95, 87, 84, 91, 86, 82, 90, 83, 85]
List13: [10, 15, 8, 12, 20, 18, 25, 30, 22, 17, 14, 28, 19, 24, 16, 21, 23, 27, 26, 11, 13, 9, 29, 31, 32]
Distances >20: [25, 30, 22, 28, 24, 21, 23, 27, 26, 29, 31, 32]
List14: [50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100, 45, 52, 58, 62, 68, 72, 77, 83, 88, 93, 97, 54, 59, 64]
Weights >70: [75, 80, 85, 90, 95, 100, 72, 77, 83, 88, 93, 97]
List15: [150, 155, 160, 165, 170, 175, 180, 185, 190, 195, 152, 158, 163, 168, 173, 178, 183, 188, 193, 198, 151, 156, 161, 166, 171]
Heights >170: [175, 180, 185, 190, 195, 173, 178, 183, 188, 193, 198, 171]
List16: [25000, 30000, 35000, 40000, 45000, 50000, 55000, 60000, 65000, 70000, 32000, 37000, 42000, 47000, 52000, 57000, 62000, 67000, 72000, 77000, 33000, 38000, 43000, 48000, 53000]
Salaries >50000: [55000, 60000, 65000, 70000, 52000, 57000, 62000, 67000, 72000, 77000, 53000]
List17: [23, 25, 28, 30, 35, 27, 26, 29, 32, 31, 24, 22, 33, 34, 36, 38, 40, 26, 28, 30, 27, 29, 31, 32, 33]
Ages >30: [35, 32, 31, 33, 34, 36, 38, 40, 31, 32, 33]
List18: [20, 22, 25, 18, 30, 28, 19, 17, 26, 24, 21, 23, 29, 27, 20, 18, 19, 22, 25, 21, 20, 23, 26, 24, 22]
Temp >25: [30, 28, 26, 29, 27, 26]
List19: [55, 60, 65, 70, 75, 80, 85, 90, 95, 50, 52, 58, 62, 68, 72, 77, 83, 88, 93, 97, 54, 59, 64, 69, 74]
Marks >=70: [70, 75, 80, 85, 90, 95, 72, 77, 83, 88, 93, 97, 74]
List20: [88, 92, 76, 85, 79, 91, 83, 87, 95, 80, 72, 68, 84, 77, 90, 86, 81, 78, 89, 93, 75, 82, 88, 94, 79]
Scores >85: [88, 92, 91, 87, 95, 90, 86, 89, 93, 88, 94]
List21: [5, 8, 12, 15, 20, 18, 25, 30, 22, 17, 14, 28, 19, 24, 16, 21, 23, 27, 26, 11, 13, 9, 29, 31, 32]
Distances >20: [25, 30, 22, 28, 24, 21, 23, 27, 26, 29, 31, 32]
List22: [120, 150, 180, 200, 220, 250, 280, 300, 320, 350, 125, 155, 185, 205, 225, 255, 285, 305, 325, 355, 130, 160, 190, 210, 230]
Pages >250: [280, 300, 320, 350, 255, 285, 305, 325, 355]
List23: [4.2, 3.8, 4.5, 4.0, 3.5, 4.8, 4.1, 3.9, 4.6, 4.3, 4.0, 3.7, 4.4, 4.2, 3.9, 4.5, 4.7, 4.1, 3.8, 4.6, 4.3, 4.0, 4.2, 4.4, 4.1]
Ratings >=4.5: [4.5, 4.8, 4.6, 4.5, 4.7, 4.6]
List24: [100, 150, 200, 250, 300, 120, 180, 220, 260, 280, 140, 190, 230, 270, 310, 330, 170, 210, 250, 290, 320, 360, 380, 400, 420]
Prices >250: [300, 260, 280, 270, 310, 330, 290, 320, 360, 380, 400, 420]
List25: [50, 60, 70, 80, 90, 55, 65, 75, 85, 95, 40, 45, 55, 65, 75, 85, 95, 50, 60, 70, 80, 90, 100, 110, 120]
Inventory >80: [90, 85, 95, 85, 95, 90, 100, 110, 120]
Total Inventory: 1865